#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

command="$@"
project="ffc-elm-apply"
service="app"

if [ "${command}" = "" ]; then
  command="npm test"
fi

compose() {
  # Remove STUB_COMPLIANCE_SERVICE=false once the compliance API is available and the temporary hack to stub it is removed
  LOG_REQUESTS=false STUB_COMPLIANCE_SERVICE=false docker-compose -p "${project}-test" $@
}

(
  cd "${projectRoot}"

  # Guarantee clean environment
  compose down --volumes

  # Ensure container images are up to date
  compose build

  # Run tests
  compose run ${service} ${command}

  # Clean up
  compose down --volumes
)
